config/routes.rb
Rails.application.routes.draw do
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users

  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :profile, foreign_key: :profile_id
  belongs_to :area, foreign_key: :area_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :secure_validatable, :timeoutable,
         :password_expirable, :password_archivable , :confirmable, :lockable, :expirable , :authentication_keys => [:login]

  validates :user_name, :presence => true, :uniqueness => { :case_sensitive => false }

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.user_name || self.email
  end

  #def current_user
  #@current_user ||= User.find(session[:id])
  #end

  def self.find_for_database_authentication(warden_conditions)

    conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      #where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      where(conditions).where(["user_name = :value OR lower(email) = lower(:value)", { :value => login }]).first

    else

      where(conditions.to_h).first

    end

  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super

    @users = User.all.count
    @usern = params[:user][:user_name]
    @usera = params[:user][:area_id]

    if @user.save
      @user.name = @user.name.titleize
      @user.last_name = @user.last_name.titleize
      @user.employment = @user.employment.titleize
      @user.boss_name = @user.boss_name.titleize
      @user.save
      #---------------------------------------------------------------------------- ASIGNACIÓN DE PERFIL Y ENVIO DE CORREOS A USUARIOS ADMINISTRADORES

      # Si no hay usuarios, el perfil asignado es Administrador Central
      if @users == 1
        @user.profile_id = 1
        @user.save

      else # Si hay al menos un usuario
        if @usera == "1" # si selecciona Central, se asigna perfil Default de Central
          @perfil = Profile.find_by(flag: 1, area_id: @usera)

          @user.profile_id = @perfil.id
          @user.save

          # Se envía correo a los Administradores Centrales
          @admina = Profile.find_by_flag(0)
          @admin = User.where("profile_id = ?", @admina.id)
          @admin.each do |f|
            @email = f.email
            ChangePerfil.mandar_permisos_signup(@user, @email).deliver
          end

        else # Es otra área
          @area_users = User.where("area_id = ?", @usera).count

          if @area_users <= 1 # Si no existen usuarios en el área, se asigna perfil administrador del Área
            @perfil = Profile.find_by(flag: 1, area_id: @usera)

            @user.profile_id = @perfil.id
            @user.save

            # Se envía correo a los Administradores Centrales
            @admina = Profile.find_by_flag(0)
            @admin = User.where("profile_id = ?", @admina.id)
            @admin.each do |f|
              @email = f.email
              ChangePerfil.mandar_permisos_signup(@user, @email).deliver
            end

          else #Si existen usuarios, se asigna perfil Default del Área
            @perfil = Profile.find_by(flag: 2, area_id: @usera)

            @user.profile_id = @perfil.id
            @user.save

            # Se envía correo a los Administradores de Área
            @admina = Profile.find_by(flag: 1, area_id: @usera)
            @admin = User.where("profile_id = ?", @admina.id)
            @admin.each do |f|
              @email = f.email
              ChangePerfil.mandar_permisos_signup(@user, @email).deliver
            end
          end
        end
      end
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_filter :verify_authenticity_token
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    @valorEnvio = params[:valorEnvio]
    @user = User.where("user_name = ? OR email= ?", @valorEnvio, @valorEnvio)
    @user.each do |u|
      @cua = u.activo
    end
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/_activate.html.erb
<%= form_for(user) do |f| %>
    <div class="actions">
      <% lastAc = User.find(params[:id])%>
      <input type="hidden" value="<%= lastAc.last_activity_at %>" name="valorPasado">
      <input type="hidden" value="<%= params[:id] %>">
      <center><%= f.submit t('views.users_activate.activate'), :class => 'btn btn-success' %></center>
    </div>
<% end %>

app/views/users/_form.html.erb
<script>
    jQuery(function ($) {
        $("#phones").mask("(99) 9999-9999");
    });

    jQuery(function ($) {
        $("#phones").mask("(99) 9999-9999");
    });

</script>
<script>
    jQuery(function ($) {
        $("#exts").mask("9999");
    });

    jQuery(function ($) {
        $("#exts").mask("9999");
    });

</script>
<% user = User.find(params[:id]) %>
<%= form_for(user) do |f| %>
    <script>
      var id = "<%= user.id %>"
    </script>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-xs-2 col-lg-2"></div>
      <div class="col-xs-6 col-lg-7">
        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <p class="text-center">
                <label><%= t('activerecord.atributes.name') %></label>
                <%= f.text_field :name, :class => 'form-control', :required => true, :maxlength => '255', autocomplete: "off" %>
              </p>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="field">
              <p class="text-center">
                <label><%= t('activerecord.atributes.last_name') %></label>
                <%= f.text_field :last_name, :class => 'form-control', :required => true, :maxlength => '255', autocomplete: "off" %>
              </p>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <div align="center" class="form-group">
                <label><%= t('activerecord.atributes.phone') %></label>
                <!--<input type="text" class="form-control" >-->
                <%= f.text_field :phone, :id => "phones", class: "form-control", :required => true, autocomplete: "off", :data_mask => "(55) 99-99-99-99" %>
              </div>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="field">
              <p class="text-center">
                <label><%= t('activerecord.atributes.ext') %></label>
                <%= f.text_field :ext, :class => 'form-control', :autocomplete => "off", :data_mask => "999", :data_mask => "9999",:id => "exts" %>
              </p>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <p class="text-center">
                <label><%= t('activerecord.atributes.boss_name') %></label>
                <%= f.text_field :boss_name, :class => 'form-control', :required => true, autocomplete: "off", :maxlength => '255' %>
              </p>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="field">
              <p class="text-center">
                <label><%= t('activerecord.atributes.employment') %></label>
                <%= f.text_field :employment, :class => 'form-control', :required => true, autocomplete: "off", :maxlength => '255' %>
              </p>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-xs-12">

            <div>
              <p>
              <center>
                <%= f.label  t('activerecord.atributes.area'), {:id => 'labelArea'} %>
                <%#= f.collection_select :area_id, Area.order(:id), :id, :name, {:include_blank => t('views.users_change.placeh_area_u_change')}, { :id => 'areaSel', :class => 'form-control', :style => 'width: 250px;'} %>
                <select class="form-control" id="areaSel" name="user[area_id]" style="width: 250px">
                  <option value=""> <%= t('views.users_change.placeh_area_u_change') %> </option>
                  <% @areas.each do |ar| %>
                      <option value="<%= ar[:id] %>"><%= ar[:name] %></option>
                  <% end %>
                </select>
              </center>
              </p>
            </div>

            <div>
              <center>
                <%= f.label t('activerecord.atributes.profile_id'), {:style => 'display: none;', :id => 'labelProfile'} %>
                <select id="perfil" name="user[profile_id]" class="form-control" style="width: 250px; display: none;">
                  <option value=""><%= t('views.users_change.placeh_profile_u_change') %></option>
                </select>
              </center>
            </div>

          </div>
        </div>
      </div>
      <div class="col-xs-1"></div>
      <div class="col-xs-3 col-lg-2 text-center">
        <ul class="nav nav-pills nav-stacked">
          <% if @crearPerfil == 8%>
              <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + t('views.users_show.create_profile_u_show'), new_profile_path, :class => 'btn btn-sm btn-primary dim' %>
          <% end %>

        </ul>
      </div>
      <div class="row">
        <div class="col-xs-12 hr-line-dashed"></div>
        <div class="col-xs-12">
          <div class="actions">
            <button type="submit" , class="btn btn-xs btn-primary " , value="<%= t('views.users_edit.save_u_edit') %>" , name="btnSave">
              <i class="fa fa-users"></i>  <%= t('views.users_edit.save_u_edit') %>
            </button>
            <% if @leerUser == 2 %>
                <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('views.users_edit.show_u_edit'), user, :class => 'btn btn-xs btn-primary dim' %>
            <% end %>
            <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
          </div>
        </div>
      </div>
    </div>
<% end %>


<script>
    var flag = "<%= @current_user_flag %>"
    var area = "<%= @current_user_area %>"
    var bel = "<%= @current_user_store %>"

</script>

<script>
    $("#areaSel").click(function () {
        $("#areaSel").change(function () {
            var valor = $(this).val()

            if (valor == "") {
                $("#perfil").hide();
                $("#labelProfile").hide();
                $("#btnChange").hide()
            }
            else {
                $("#perfil option").remove();
                $("#perfil").show();
                $("#labelProfile").show();

                if(area == 1){ //Central muestro todos los perfiles disponibles en el área
                    if (valor == 1){
                        $("#perfil").append($("<option value></option>").text("<%= t('views.users_edit.placeh_profile_u_edit') %>"));
                        for (i = 0; i < gon.pflag.length; i++) {
                            if (gon.pflag[i].area_id == valor && gon.pflag[i].flag != 1) {
                                $("#perfil").append($("<option></option>")
                                    .attr("value", gon.pflag[i].id)
                                    .text(gon.pflag[i].name));
                            }
                        }
                    }else{
                        $("#perfil").append($("<option value></option>").text("<%= t('views.users_edit.placeh_profile_u_edit') %>"));
                        for (i = 0; i < gon.pflag.length; i++) {
                            if (gon.pflag[i].area_id == valor && gon.pflag[i].flag != 2) {
                                $("#perfil").append($("<option></option>")
                                    .attr("value", gon.pflag[i].id)
                                    .text(gon.pflag[i].name));
                            }
                        }
                    }

                }else { //Si no es área central sólo muestro los perfiles que tengan bandera mayor a la mía (menor rango)
                    $("#perfil").append($("<option value></option>").text("<%= t('views.users_edit.placeh_profile_u_edit') %>"));
                    for (i = 0; i < gon.pflag.length; i++) {
                        if (gon.pflag[i].area_id == valor && gon.pflag[i].flag >= flag && gon.pflag[i].flag != 2) {
                            $("#perfil").append($("<option></option>")
                                .attr("value", gon.pflag[i].id)
                                .text(gon.pflag[i].name));
                        }
                    }
                }

            }


        })
    })
</script>

<script>
    $('#edit_user_'+ id).validate({
        messages: {
            "user[name]": {
                required: "<%= t('all.requi')%>"
            },
            "user[last_name]": {
                required: "<%= t('all.requi')%>"
            },
            "user[phone]": {
                required: "<%= t('all.requi')%>"
            },
            "user[ext]": {
                required: "<%= t('all.requi')%>"
            },
            "user[boss_name]": {
                required: "<%= t('all.requi')%>"
            },
            "user[employment]": {
                required: "<%= t('all.requi')%>"
            },
            "belongs": {
                required: "<%= t('all.requi')%>"
            },
            "user[store_id]": {
                required: "<%= t('all.requi')%>"
            },
            "user[area_id]": {
                required: "<%= t('all.requi')%>"
            },
            "user[nameProfile_id]": {
                required: "<%= t('all.requi')%>"
            }
        }
    });
</script>

app/views/users/askpermissions.html.erb
<div id="head">
  <h1><%= t('views.users_ask_permissions.title_u_ask') %></h1>
  <br>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4" id="inner-body">
    <p class="text-center">
      <h4>
    <p class="text-center"><%= t('views.users_ask_permissions.messages') %></p></h4>

    <%#= form_tag(, :method => "post") do %>

    <%= form_tag({:controller => "users", :action => "askpermissions"}, {:method => "get"}) do %>
        <br>
        <table class="table table-striped table-hover  table-responsive" style="margin: 0 auto; text-align: center;">
          <thead>
          <tr>
            <th><%= t('views.users_ask_permissions.attribute') %></th>
            <th><%= t('activerecord.atributes.crear') %></th>
            <th><%= t('activerecord.atributes.editar') %></th>
            <th><%= t('activerecord.atributes.editar') %></th>
            <th><%= t('activerecord.atributes.eliminar') %></th>
          </tr>
          </thead>
          <tbody>

          <tr>
            <td>
              <label><%= t('views.permisos_edit.users') %></label>
              <input type="hidden" name="name1" value="Users">
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="8" name="crear1"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="4" name="editar1"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="2" name="leer1"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="eliminar1"><br>
            </td>
          </tr>

          <tr>
            <td>
              <label><%= t('views.permisos_edit.profiles') %></label>
              <input type="hidden" name="name2" value="Profiles">
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="8" name="crear2"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="4" name="editar2"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="2" name="leer2"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="eliminar2"><br>
            </td>
          </tr>

          <tr>
            <td>
              <label><%= t('views.permisos_edit.areas') %></label>
              <input type="hidden" name="name3" value="Areas">
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="8" name="crear3"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="4" name="editar3"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="2" name="leer3"><br>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="eliminar3"><br>
            </td>
          </tr>

          </tbody>
        </table>
        <br>
        <h5><label><%= t('views.users_ask_permissions.extra_comments') %></label></h5>
        <textarea class="form-control" rows="3" name="coment"></textarea>
        <br>
        <p class="text-center">
          <%= submit_tag t('views.users_ask_permissions.ask_for_permissions'), :class => 'btn btn-primary m-b' %>
        </p>
    <% end %>

  </div>
  <div class="col-md-4"></div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="text-left">
      <%= link_to t('views.users_ask_permissions.back_u_ask'), home_index_path, :class => 'btn btn-primary m-b' %>
    </p></div>
</div>

</div>

app/views/users/show.html.erb
<div class="row" id="Panel">
  <div class="col-xs-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.users_show.title_u_show') %></h1>
      </div>
      <div class="ibox-content">
        <div class="row">
          <div class=" col-xs-9"></div>
          <div class="col-xs-1">
            <div class="row">
              <div class="col-xs-4"></div>
              <div class="col-xs-6 text-right">
                <% @act = @user.last_activity_at %>
                <% if !@user.last_activity_at.nil? %>
                  <% if (@user.last_activity_at < 1.month.ago) %>
                    <% if @editarUser == 4 && (@user.id != current_user.id.to_i) %>
                      <% @perfil = Profile.find(@user.profile_id) %>

                      <% if current_user.profile.area_id == "1" #Es un usuario de CENTRAL       %>
                        <% if (@perfil.flag > current_user.profile.flag.to_i) %>
                          <%= render 'activate', user: @user %>
                        <% end %>
                      <% else #Es un usuario de OTRA AREA   %>
                        <% if @perfil.flag > current_user.profile.flag.to_i && @user.area_id.to_i == current_user.profile.area_id.to_i %>
                          <%= render 'activate', user: @user %>
                        <% end %>
                        <% if @perfil.flag >= current_user.profile.flag.to_i && @user.area_id.to_i > current_user.profile.area_id.to_i %>
                          <%= render 'activate', user: @user %>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% else %>
                  <% if @editarUser == 4 && (@user.id != current_user.id.to_i) %>
                    <% @perfil = Profile.find(@user.profile_id) %>
                    <% if current_user.profile.area_id == "1" #Es un usuario de CENTRAL       %>
                      <% if (@perfil.flag > current_user.profile.flag.to_i) %>
                        <%= render 'activate', user: @user %>
                      <% end %>
                    <% else #Es un usuario de OTRA AREA   %>
                      <% if @perfil.flag > current_user.profile.flag.to_i && @user.area_id.to_i == current_user.profile.area_id.to_i %>
                        <%= render 'activate', user: @user %>
                      <% end %>
                      <% if @perfil.flag >= current_user.profile.flag.to_i && @user.area_id.to_i > current_user.profile.area_id.to_i %>
                        <%= render 'activate', user: @user %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <div class="col-xs-2"></div>
            </div>
          </div>
          <div class=" col-xs-2"></div>
        </div>

        <div class="row">
          <div class="col-xs-2"></div>
          <div class="col-xs-7">
            <p class="text-center">
              <strong><%= t('activerecord.atributes.name') %>:</strong>
              <%= @user.name %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.last_name') %>:</strong>
              <%= @user.last_name %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.boss_name') %>:</strong>
              <%= @user.boss_name %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.phone') %>:</strong>
              <%= @user.phone %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.ext') %>:</strong>
              <%= @user.ext %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.employment') %>:</strong>
              <%= @user.employment %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.area_id') %>:</strong>
              <%#= @users.area %>
              <% if @user.area.present? %>
                <% if @user.area.name.present? %>
                  <%= @user.area.name %>
                <% end %>
              <% else %>
                N/A
              <% end %>
            </p>

            <p class="text-center">
              <strong><%= t('activerecord.atributes.profile_id') %>:</strong>
              <%#= @users.perfil.name %>
              <% if @user.profile.present? %>
                <% if @user.profile.name.present? %>
                  <%= @user.profile.name %>
                <% end %>
              <% else %>
                N/A
              <% end %>
            </p>
          </div>
          <div class="col-xs-2 text-right">
            <ul class="nav nav-pills nav-stacked">
              <% if @crearPerfil == 8 %>
                <p class="text-center">
                  <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + t('views.users_show.create_profile_u_show'), new_profile_path, :class => 'btn btn-sm btn-primary dim' %>
                </p>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-1"></div>
        </div>
        <% if @editarUser == 4 && (@user.id != current_user.id.to_i) %>
          <% @perfil = Profile.find(@user.profile_id) %>

          <% if current_user.profile.area_id == 1 #Es un usuario de CENTRAL      %>
            <% if (@perfil.flag > current_user.profile.flag.to_i) %>
              <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-7">
                  <%= render 'change', user: @user %>
                </div>
                <div class="col-xs-3"></div>
              </div>

              <div class="col-xs-12 hr-line-dashed"></div>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('views.users_show.edit_u_show'), edit_user_path(@user), :class => 'btn btn-xs btn-primary dim' %>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
            <% else %>
              <div class="col-xs-12 hr-line-dashed"></div>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
            <% end %>
          <% else #Es un usuario de OTRA AREA  %>
            <% if @perfil.flag > current_user.profile.flag.to_i && @user.area_id == current_user.profile.area_id %>
              <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-7">
                  <%= render 'change', user: @user %>
                </div>
                <div class="col-xs-3"></div>
              </div>

              <div class="col-xs-12 hr-line-dashed"></div>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('views.users_show.edit_u_show'), edit_user_path(@user), :class => 'btn btn-xs btn-primary dim' %>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
            <% end %>
            <% if @perfil.flag >= current_user.profile.flag.to_i && @user.area_id.to_i > current_user.profile.area_id.to_i %>
              <div class="row">
                <div class="col-xs-2"></div>
                <div class="col-xs-7">
                  <%= render 'change', user: @user %>
                </div>
                <div class="col-xs-3"></div>
              </div>

              <div class="col-xs-12 hr-line-dashed"></div>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('views.users_show.edit_u_show'), edit_user_path(@user), :class => 'btn btn-xs btn-primary dim' %>
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
            <% end %>
          <% end %>
        <% else %>
          <div class="col-xs-12 hr-line-dashed"></div>
          <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + t('all.back'), users_path, :class => 'btn btn-xs btn-primary dim' %>
        <% end %>
      </div>


    </div>
  </div>
</div>