config/routes.rb
Rails.application.routes.draw do
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users

  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/area.rb
class Area < ApplicationRecord
  # has_many :subarea, class_name: "Area",
  #          foreign_key: "area_id"
  #
  # belongs_to :area_master, class_name: "Area"
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  @@byArea = "Areas"
  # GET /areas
  # GET /areas.json
  def index
    if current_user
      @page = "Areas"
      @user = current_user.name
      @user_id = current_user.id
      @userl = current_user.last_name
      @action = "3"
      @account = "not yet"
      @lasac = "not available"
      @cli_id = 0
      @date = Time.now
      # @description = General.all.count.to_i

      # @historic = Historic.new
      # @historic.page = @page
      # @historic.user_name = @user + " " + @userl
      # @historic.user_id = @user_id
      # @historic.action = @action
      # @historic.account = @account
      # @historic.last_account = @lasac
      # @historic.client_id = @cli_id
      # @historic.date = @date
      # @historic.description = @description
      # @historic.save


      @cu = current_user.profile_id

      if @cu != 0

        @per = Permission.where("view_name = 'Areas' and profile_id = ?", @cu)

        @per.each do |permisos|
          @uno = permisos.view_name
          @crearArea = permisos.crear
          @editarArea = permisos.editar
          @leerArea = permisos.leer
          @eliminarArea = permisos.eliminar

          if permisos.view_name == @@byArea

            @@crear = permisos.crear
            @@editar = permisos.editar
            @@leer = permisos.leer
            @@eliminar = permisos.eliminar

            @crear = permisos.crear
            @editar = permisos.editar
            @leer = permisos.leer
            @eliminar = permisos.eliminar
          end

        end

        if ((@@crear == 8) || (@@editar == 4) || (@@leer == 2) || (@@eliminar == 1))

          @area_usuario = current_user.area_id

          if @area_usuario == "1"
            @areas = Area.all.page(params[:page]).per(10)

            areas_arr = Array.new

            @areas.each do |ar|
              valor = {id: '', name: '', area_id: ''}
              valor[:id] = ar.id
              valor[:name] = ar.name
              valor[:area_id] = ar.area_id

              areas_arr.push(valor)
            end

            @areas = Kaminari.paginate_array(areas_arr).page(params[:page]).per(10)
          else
            @areas = Area.where("id = ?", @area_usuario)

            areas_arr = Array.new

            @areas.each do |ar|
              @nombre = ar.name
              valor = {id: '', name: '', area_id: ''}
              valor[:id] = ar.id
              valor[:name] = ar.name
              valor[:area_id] = ar.area_id

              areas_arr.push(valor)

              @subarea_1 = Area.where("area_id = ?", ar.id)

              if !@subarea_1.nil?

                @subarea_1.each do |sub|
                  valor = {id: '', name: '', area_id: ''}
                  valor[:id] = sub.id
                  valor[:name] = sub.name
                  valor[:area_id] = sub.area_id

                  areas_arr.push(valor)

                  @subarea_2 = Area.where("area_id = ?", sub.id)

                  if !@subarea_2.nil?

                    @subarea_2.each do |sub2|
                      valor = {id: '', name: '', area_id: ''}
                      valor[:id] = sub2.id
                      valor[:name] = sub2.name
                      valor[:area_id] = sub2.area_id

                      areas_arr.push(valor)

                      @subarea_3 = Area.where("area_id = ?", sub2.id)

                      if !@subarea_3.nil?

                        @subarea_3.each do |sub3|
                          valor = {id: '', name: '', area_id: ''}
                          valor[:id] = sub3.id
                          valor[:name] = sub3.name
                          valor[:area_id] = sub3.area_id

                          areas_arr.push(valor)

                          @subarea_4 = Area.where("area_id = ?", sub3.id)

                          if !@subarea_4.nil?

                            @subarea_4.each do |sub4|
                              valor = {id: '', name: '', area_id: ''}
                              valor[:id] = sub4.id
                              valor[:name] = sub4.name
                              valor[:area_id] = sub4.area_id

                              areas_arr.push(valor)

                              @subarea_5 = Area.where("area_id = ?", sub4.id)

                              if !@subarea_5.nil?

                                @subarea_5.each do |sub5|
                                  valor = {id: '', name: '', area_id: ''}
                                  valor[:id] = sub5.id
                                  valor[:name] = sub5.name
                                  valor[:area_id] = sub5.area_id

                                  areas_arr.push(valor)

                                  @subarea_6 = Area.where("area_id = ?", sub5.id)

                                  if !@subarea_6.nil?

                                    @subarea_6.each do |sub6|
                                      valor = {id: '', name: '', area_id: ''}
                                      valor[:id] = sub6.id
                                      valor[:name] = sub6.name
                                      valor[:area_id] = sub6.area_id

                                      areas_arr.push(valor)

                                      @subarea_7 = Area.where("area_id = ?", sub6.id)

                                      if !@subarea_7.nil?

                                        @subarea_7.each do |sub7|
                                          valor = {id: '', name: '', area_id: ''}
                                          valor[:id] = sub7.id
                                          valor[:name] = sub7.name
                                          valor[:area_id] = sub7.area_id

                                          areas_arr.push(valor)

                                          @subarea_8 = Area.where("area_id = ?", sub7.id)

                                          if !@subarea_8.nil?

                                            @subarea_8.each do |sub8|
                                              valor = {id: '', name: '', area_id: ''}
                                              valor[:id] = sub8.id
                                              valor[:name] = sub8.name
                                              valor[:area_id] = sub8.area_id

                                              areas_arr.push(valor)

                                              @subarea_9 = Area.where("area_id = ?", sub8.id)

                                              if !@subarea_9.nil?

                                                @subarea_9.each do |sub9|
                                                  valor = {id: '', name: '', area_id: ''}
                                                  valor[:id] = sub9.id
                                                  valor[:name] = sub9.name
                                                  valor[:area_id] = sub9.area_id

                                                  areas_arr.push(valor)

                                                  @subarea_10 = Area.where("area_id = ?", sub9.id)

                                                  if !@subarea_10.nil?

                                                    @subarea_10.each do |sub10|
                                                      valor = {id: '', name: '', area_id: ''}
                                                      valor[:id] = sub10.id
                                                      valor[:name] = sub10.name
                                                      valor[:area_id] = sub10.area_id

                                                      areas_arr.push(valor)
                                                    end
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end

            @areas = Kaminari.paginate_array(areas_arr).page(params[:page]).per(10)
          end
          if params[:search].present?
            @belongs = params[:search].to_s

            if @belongs == "Central Office" || @belongs == "Oficina Central" || @belongs == "Central Office\t" || @belongs == "Oficina Central\t" || @belongs == "Central Office\t\t" || @belongs == "Oficina Central\t\t" || @belongs == "central office" || @belongs == "oficina central" || @belongs == "central office\t" || @belongs == "oficina central\t" || @belongs == "central office\t\t" || @belongs == "oficina central\t\t"
              @belongs= nil
              @busco = "2"
            elsif @belongs == "Store" || @belongs == "Tienda" || @belongs == "Store\t" || @belongs == "Tienda\t" || @belongs == "Store\t\t" || @belongs == "Tienda\t\t" || @belongs == "store" || @belongs == "tienda" || @belongs == "store\t" || @belongs == "tienda\t" || @belongs == "store\t\t" || @belongs == "tienda\t\t"
              @belongs = "1"
              @busco = "1"
            end

            name = params[:search]
            name = name.gsub! /\t/, ''
            if name.nil?
              @na = params[:search].to_s
            else
              @na = name
            end

            if !Area.find_by_name(@na).nil?
              @areas = Area.where("name = ?", @na).page(params[:page]).per(10)
              @query = params[:search]
            elsif !Area.find_by_store_id(@belongs).nil?

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(area) do |f| %>
    <% if area.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

          <ul>
            <% area.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">

        <div class="field">
          <%= f.label t('all.name') %>
          <%= f.text_field :name, :class => 'form-control', :required => true, :id => 'nombre', autocomplete: "off", :maxlength => '255' %>
          <input type="hidden" name="nombrePas" id="nombrePas">
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">

        <% if @areas.length > 0 %>
            <div class="field">
              <br>
              <label><%= t('views.areas_form.subarea') %></label>
              <br>
              <input type="checkbox" class="i-checks yes" value="1" name="subarea_yes" id="subarea_yes">&nbsp;<%= t('views.areas_form.yes') %>
              <br>
              <input type="checkbox" class="i-checks no" value="0" name="subarea_no" id="subarea_no">&nbsp;<%= t('views.areas_form.no') %>
              <input type="hidden" name="nombrePas" id="nombrePas">
            </div>
        <% end %>
      </div>
      <div class="col-md-3"></div>
    </div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="field">

          <% if action_name == "new" %>
              <label id="label_area" style="display: none;"><%= t('views.areas_form.below_new') %></label>
              <select class="form-control" id="area_id" style="display: none;" name="area[area_id]">
                <option value=""> <%= t('views.profiles_new.placeh_area') %> </option>
                <% @areas.each do |ar| %>
                    <option value="<%= ar[:id] %>"><%= ar[:name] %></option>
                <% end %>
              </select>
          <% else %>
              <% if @areas.length > 1 %>
                  <label id="label_area" style="display: none;"><%= t('views.areas_form.below_edit') %></label>
                  <select class="form-control" id="area_id" style="display: none;" name="area[area_id]">
                    <option value=""> <%= t('views.profiles_new.placeh_area') %> </option>
                    <% @areas.each do |ar| %>
                        <% if ar[:id] != area.id %>
                            <option value="<%= ar[:id] %>"><%= ar[:name] %></option>
                        <% end %>
                    <% end %>
                  </select>
                  <script>
                      $(function () {
                          <% if !area.area_id.nil? %>
                          $('input.yes').iCheck('check');

                          $('#area_id option[value="<%= area.area_id %>"]').prop('selected', true)
                          <% else %>
                          $('input.no').iCheck('check');
                          <% end %>
                      })
                  </script>
              <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
    <div class="col-md-12 hr-line-dashed"></div>
    <div class="row">
      <div class="col-md-12">
        <div class="actions">
          <button type="submit" , class="btn btn-xs btn-primary " , value="<%= t('all.save') %>" , name="btnSave">
            <i class="fa fa-sticky-note"></i>  <%= t('all.save') %>
          </button>
          <%= link_to '<span class="fa fa-sticky-note" ></span>  '.html_safe + t('all.back'), areas_path, :class => 'btn btn-xs btn-primary dim' %>
        </div>
      </div>
    </div>
    <script>
        var id = "<%= area.id%>"

    </script>
<% end %>
<script type="text/javascript">
    var elem = document.querySelector('.js-switch');
    var switchery = new Switchery(elem, {color: '#1AB394'});
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });
</script>

<script>
    $(document).ready(function () {
        var pasado = $("#nombre").val();
        $("#nombrePas").val(pasado);
    });

    $('#new_area').validate({
        messages: {
            "area[name]": {
                required: "<%= t('all.requi')%>"
            }
        }
    });

    $('#edit_area_' + id).validate({
        messages: {
            "area[name]": {
                required: "<%= t('all.requi')%>"
            }
        }
    });

    $('input.yes').on('ifChecked', function () {
        $('input.no').iCheck('uncheck');

        $("#label_area").show()
        $("#area_id").show()
    });

    $('input.no').on('ifChecked', function () {
        $('input.yes').iCheck('uncheck');

        $("#label_area").hide()
        $("#area_id").hide()
    });


</script>

app/views/areas/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.areas_edit.title_e') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <%= render 'form', area: @area %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/areas/index.html.erb
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('table').footable({paginate: false});
    });
</script>

<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('all.areas') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <% if @error.present? %>
            <!--<div class="alert alert-danger alert-dismissable fade in">-->
            <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>-->
            <!--<%#= @error %>-->
            <!--</div>-->
            <script>
                swal({
                    title: "<%= t('all.no_filter')%>",
                    type: "warning"

                }); // swal
            </script>
        <% end %>

        <%= form_tag({:controller => "areas", :action => "index"}, :method => "get") do %>
            <input type="hidden" value="<%= params[:locale] %>" name="locale">
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <input type="text" class="form-control" name="search" autocomplete="off" placeholder="<%= t('all.placehol_search') %>">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <div class="btn-group">
                    <%#= submit_tag t('all.btn_search'), :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>

                    <%= button_tag(type: 'submit', class: 'btn btn-w-m btn-info') do %>
                        <i class="fa fa-search"></i>
                        <%= t('all.btn_search') %>
                    <% end %>
                  </div>
                </div>
              </div>

            </div>

        <% end %>

        <% if @query.present? %>

            <div class="row">
              <div class="col-lg-4">
                <h3><%= t('all.query') %>: <%= @query %></h3>
              </div>
              <div class="col-lg-8">
                <div class="row">
                  <div class="col-xs-6 col-sm-4">
                    <div class="form-group">
                      <%= link_to t('all.clean'), areas_path, :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>
                    </div>

                  </div>
                </div>
              </div>
            </div>
        <% end %>


        <div class="row">
          <div class="col-sm-4">
            <br>
            <br>
            <% if @crearArea == 8 %>
                <%= link_to '<span class="fa fa-sticky-note"></span> '.html_safe + t('views.areas_index.new'), new_area_path, :class => 'btn btn-xs btn-info dim' %>
            <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="detall_left">
                <%= page_entries_info @areas, entry_name: t('activerecord.models.areas') %>
              </div>
              <div class="pag_right">
                <%= paginate @areas, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
            </div>
          </div>
        </div>
        <div class="table table-responsive overflow col-sm-3" tabindex="5005" style="overflow: hidden; outline: none;">
          <table class="table footable no-paging" data-filter=#filter data-page-size="10">
            <thead>
            <tr>
              <th class="text-center" data-sort-ignore="true"><%= t('all.name') %></th>
              <th class="text-center" data-sort-ignore="true"><%= t('views.areas_index.subarea') %></th>
              <th class="text-center" data-sort-ignore="true"><%= t('views.areas_index.edit') %></th>
              <th class="text-center" data-sort-ignore="true"><%= t('views.areas_index.destroy') %></th>
            </tr>
            </thead>

            <tbody>
            <% if current_user.area_id == "1" %>
                <% @areas.each do |area| %>

                    <tr>
                      <td class="text-center"><%= area[:name] %></td>
                      <td class="text-center">
                        <% if area[:area_id].nil? %>
                            N/A
                        <% else %>
                            <% @ar = Area.find(area[:area_id]) %>
                            <%= @ar.name  %>
                        <% end %>
                      </td>
                      <td class="text-center">
                        <% if @editarArea == 4 && area[:id] != 1 %>
                            <%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil "></i></button>'.html_safe, edit_area_path(area), :data => {:no_turbolink => false} %>
                        <% end %>
                      </td>
                      <td class="text-center">
                        <% if @eliminarArea == 1 && area[:id] != 1 %>
                            <input type="hidden" value="<%= area[:name] %>" id="area<%= area[:id] %>">
                            <%#= link_to '<button class="btn btn-danger btn-xs areas" type="button"><i class="fa fa-trash-o "></i></button>'.html_safe, area, method: :delete, data: {confirm: t('views.areas_index.confirm')}, :id => area.id %>
                            <button class="btn btn-danger btn-xs  areas" type="button" id="<%= area[:id] %>">
                              <i class="fa fa-trash-o"></i>
                            </button>
                        <% end %>
                      </td>

                    </tr>
                <% end %>
            <% else %>
                <% @areas.each do |area| %>
                    <tr>
                      <td class="text-center"><%= area[:name] %></td>
                      <td class="text-center">
                        <% if area[:area_id].nil? %>
                        N/A
                        <% else %>
                            <% @ar = Area.find(area[:area_id]) %>
                            <%= @ar.name  %>
                        <% end %>
                        </td>
                      <td class="text-center">
                        <% if @editarArea == 4 && area[:id] != 1%>
                            <%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil "></i></button>'.html_safe, edit_area_path(area), :data => {:no_turbolink => false} %>
                        <% end %>
                      </td>
                      <td class="text-center">
                        <% if @eliminarArea == 1 && area[:id] != 1%>
                            <input type="hidden" value="<%= area[:name] %>" id="area<%= area[:id]%>">
                            <%#= link_to '<button class="btn btn-danger btn-xs areas" type="button"><i class="fa fa-trash-o "></i></button>'.html_safe, area, method: :delete, data: {confirm: t('views.areas_index.confirm')}, :id => area.id %>
                            <button class="btn btn-danger btn-xs  areas" type="button" id="<%= area[:id] %>">
                              <i class="fa fa-trash-o"></i>
                            </button>
                        <% end %>
                      </td>

                    </tr>
                <% end %>
            <% end %>

            </tbody>
            <!--<tfoot>
            <tr>
              <td colspan="11">
                <ul class="pagination pull-right"></ul>
              </td>
            </tr>
            </tfoot>-->
          </table>
        </div>
        <br>

        <div class="row">
          <div class="col-sm-4">
            <% if @crearArea == 8 %>
                <%= link_to '<span class="fa fa-sticky-note"></span> '.html_safe + t('views.areas_index.new'), new_area_path, :class => 'btn btn-xs btn-info dim' %>
            <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="pag_right">
                <%= paginate @areas, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
              <div class="detall_right">
                <%= page_entries_info @areas, entry_name: t('activerecord.models.areas') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

<script type="text/javascript">
    function checkSubmit() {
        document.getElementById("sub").value = "Sending...";
        document.getElementById("sub").disabled = true;
        return true;
    }

    $(".pop").popover({trigger: "manual", html: true, animation: false})
        .on("mouseenter", function () {
            var _this = this;
            $(this).popover("show");
            $(".popover").on("mouseleave", function () {
                $(_this).popover('hide');
            });
        }).on("mouseleave", function () {
        var _this = this;
        setTimeout(function () {
            if (!$(".popover:hover").length) {
                $(_this).popover("hide");
            }
        }, 300);
    });

    $("[data-toggle=hover]").popover({html: true})
    $('#popoverData').popover();
    /*$(document).ready(function () {
     $('table').footable();
     });*/

    function recargar() {
        window.location.reload(true);
    }

    $(".areas").click(function () {
        console.log("CLIC ELIMINAR")
    });
    $(document).on("click", ".areas", function () {
        var id = this.id;
        var area = $("#area" + id).val();
        swal({
                title: '<%= t('views.mess_apli_title')%>  ' + '<%= t('views.area')%>  ' + area + '?',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<%= t('views.mess_apli_swall_confirm')%> ",
                cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                closeOnConfirm: false,
                closeOnCancel: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal({
                            title: '<%= t('views.mess_apli_title2')%>',
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "<%= t('views.mess_apli_swall_confirm')%> ",
                            cancelButtonText: "<%= t('views.mess_apli_swall_cancel')%>",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.ajax({
                                    type: "POST",
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                                    },
                                    url: "/areas/" + id,
                                    data: {"_method": "delete"},
                                })
                                //swal("<%= t('views.mess_apli_swall')%>");
                                swal(
                                    {
                                        title: '<%= t('views.mess_apli_swall')%>',
                                        type: "success",
                                        confirmButtonText: "OK",
                                    }, function (isConfirm) {
                                        if (isConfirm) {
                                            recargar();
                                        }
                                    })
                            } else {
                                swal("<%= t('views.mess_apli_swall_cancel_1')%>");
                            }
                        })
                } else {
                    swal("<%= t('views.mess_apli_swall_cancel_1')%>");
                }
            });
    })

</script>

app/views/areas/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.areas_new.title_n') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">

        <%= render 'form', area: @area %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/areas/show.html.erb
<div id="head">
  <h1><%= t('views.areas_show.title_s')%></h1>
  <br>
</div>

<p class="text-center">
  <strong><%= t('all.name')%></strong>
  <%= @area.name %>
</p>

<p class="text-center">
  <% if @editarArea == 4 %>
      <%= link_to t('all.edit'), edit_area_path(@area), :class => 'btn btn-default' %> |
  <% end %>
  <%= link_to t('all.back'), areas_path, :class => 'btn btn-default' %>
</p>