config/routes.rb
Rails.application.routes.draw do
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users

  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/views/views/_form.html.erb
<%= form_for(view) do |f| %>
    <% if view.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(view.errors.count, "error") %> prohibited this view from being saved:</h2>

          <ul>
            <% view.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="field">
          <label><%= t('views.new_view.name') %></label>
          <%= f.text_field :name, :class => 'form-control', :required => true, :id => 'nombre', autocomplete: "off", :maxlength => '255' %>
          <input type="hidden" name="nombrePas" id="nombrePas">
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">

        <table>
          <tr>
            <td>
              <%= f.label t('views.new_view.create') %>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="view[crear]" id="view_crear">
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label t('views.new_view.edit') %>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="view[editar]" id="view_editar">
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label t('views.new_view.read') %>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="view[leer]" id="view_leer">
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label t('views.new_view.delete') %>
            </td>
            <td>
              <input type="checkbox" class="i-checks" value="1" name="view[eliminar]" id="view_eliminar">
            </td>
          </tr>
        </table>
      </div>
      <div class="col-md-4"></div>
    </div>
    <div class="col-md-12 hr-line-dashed"></div>
    <div class="row">
      <div class="col-md-12">
        <div class="actions">
          <button type="submit" , class="btn btn-xs btn-primary " , value="<%= t('all.save') %>" , name="btnSave">
            <i class="fa fa-desktop"></i>  <%= t('all.save') %>
          </button>
          <%= link_to '<span class="fa fa-desktop" ></span>  '.html_safe + t('all.back'), views_path, :class => 'btn btn-xs btn-primary dim' %>
        </div>
      </div>
    </div>
    <script>
        var id = "<%= view.id%>"

        var crear = "<%= view.crear %>"
        var editar = "<%= view.editar %>"
        var eliminar = "<%= view.eliminar %>"
        var leer = "<%= view.leer %>"

        if (crear == "1"){
            $("#view_crear").attr("checked", true)
            $("#view_crear").parent().addClass("checked")
        }
        if (editar == "1"){
            $("#view_editar").attr("checked", true)
            $("#view_editar").parent().addClass("checked")
        }
        if (eliminar == "1"){
            $("#view_eliminar").attr("checked", true)
            $("#view_eliminar").parent().addClass("checked")
        }
        if (leer == "1"){
            $("#view_leer").attr("checked", true)
            $("#view_leer").parent().addClass("checked")
        }
    </script>
<% end %>
<script type="text/javascript">
    var elem = document.querySelector('.js-switch');
    var switchery = new Switchery(elem, {color: '#1AB394'});
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });
</script>

<script>
    $(document).ready(function () {
        var pasado = $("#nombre").val();
        $("#nombrePas").val(pasado);

        console.log($("#nombrePas").val());
    });

    $('#new_view').validate({
        messages: {
            "view[name]": {
                required: "<%= t('all.requi')%>"
            },
            "belongs": {
                required: "<%= t('all.requi')%>"
            }
        }
    });

    $('#edit_view_' + id).validate({
        messages: {
            "view[name]": {
                required: "<%= t('all.requi')%>"
            },
            "belongs": {
                required: "<%= t('all.requi')%>"
            }
        }
    });
</script>
<style>
  td {
    width: 15em;
  }
</style>

app/views/views/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.views_edit.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <%= render 'form', view: @view %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/views/index.html.erb
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('table').footable({paginate: false});
    });
</script>

<div class="row">
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('all.views') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <% if @error.present? %>
            <!--<div class="alert alert-danger alert-dismissable fade in">-->
            <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>-->
            <!--<%#= @error %>-->
            <!--</div>-->
            <script>
                swal({
                    title: "<%= t('all.no_filter')%>",
                    type: "warning"

                }); // swal
            </script>
        <% end %>

        <%= form_tag({:controller => "views", :action => "index"}, :method => "get") do %>
            <input type="hidden" value="<%= params[:locale] %>" name="locale">
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <input type="text" class="form-control" name="search" autocomplete="off" placeholder="<%= t('all.placehol_search') %>">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <div class="btn-group">
                    <%#= submit_tag t('all.btn_search'), :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>

                    <%= button_tag(type: 'submit', class: 'btn btn-w-m btn-info') do %>
                        <i class="fa fa-search"></i>
                        <%= t('all.btn_search') %>
                    <% end %>
                  </div>
                </div>
              </div>

            </div>

        <% end %>

        <% if @query.present? %>

            <div class="row">
              <div class="col-lg-4">
                <h3><%= t('all.query') %>: <%= @query %></h3>
              </div>
              <div class="col-lg-8">
                <div class="row">
                  <div class="col-xs-6 col-sm-4">
                    <div class="form-group">
                      <%= link_to t('all.clean'), views_path, :class => "btn btn-w-m btn-info dim", :data => {:no_turbolink => true} %>
                    </div>

                  </div>
                </div>
              </div>
            </div>
        <% end %>


        <div class="row">
          <div class="col-sm-4">
            <br>
            <br>
            <% if @crearView == 8 %>
                <%= link_to '<span class="fa fa-desktop"></span> '.html_safe + t('all.new'), new_view_path, :class => 'btn btn-xs btn-info dim' %>
            <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="detall_left">
                <%= page_entries_info @views, entry_name: t('all.views') %>
              </div>
              <div class="pag_right">
                <%= paginate @views, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
            </div>
          </div>
        </div>
        <div class="table table-responsive overflow col-sm-3" tabindex="5005" style="overflow: hidden; outline: none;">
          <table class="table footable no-paging" data-filter=#filter data-page-size="10">
            <thead>
            <tr>
              <th class="text-center" data-sort-ignore="true"><%= t('all.name') %></th>
              <th class="text-center" data-sort-ignore="true"><%= t('views.views_index.edit') %></th>
              <th class="text-center" data-sort-ignore="true"><%= t('views.views_index.destroy') %></th>
            </tr>
            </thead>

            <tbody>
            <% @views.each do |view| %>
                <tr>
                  <td class="text-center"><%= view.name %></td>
                  <td class="text-center">
                    <% if @editarView == 4 %>
                        <%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil "></i></button>'.html_safe, edit_view_path(view), :data => {:no_turbolink => false} %>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <% if @eliminarView == 1 %>
                        <input type="hidden" value="<%= view.name %>" id="view<%= view.id %>">
                        <%#= link_to '<button class="btn btn-danger btn-xs views" type="button"><i class="fa fa-trash-o "></i></button>'.html_safe, view, method: :delete, data: {confirm: t('views.views_index.confirm')}, :id => view.id %>
                        <button class="btn btn-danger btn-xs  views" type="button" id="<%= view.id %>">
                          <i class="fa fa-trash-o"></i>
                        </button>
                    <% end %>
                  </td>

                </tr>
            <% end %>
            </tbody>
            <!--<tfoot>
            <tr>
              <td colspan="11">
                <ul class="pagination pull-right"></ul>
              </td>
            </tr>
            </tfoot>-->
          </table>
        </div>
        <br>

        <div class="row">
          <div class="col-sm-4">
            <% if @crearView == 8 %>
                <%= link_to '<span class="fa fa-desktop"></span> '.html_safe + t('all.new'), new_view_path, :class => 'btn btn-xs btn-info dim' %>
            <% end %>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-5 text-right">
            <div style="margin-bottom: 2em;">
              <div class="pag_right">
                <%= paginate @views, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>
              </div>
              <div class="detall_right">
                <%= page_entries_info @views, entry_name: t('activerecord.models.views') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

<script type="text/javascript">
    function checkSubmit() {
        document.getElementById("sub").value = "Sending...";
        document.getElementById("sub").disabled = true;
        return true;
    }

    $(".pop").popover({trigger: "manual", html: true, animation: false})
        .on("mouseenter", function () {
            var _this = this;
            $(this).popover("show");
            $(".popover").on("mouseleave", function () {
                $(_this).popover('hide');
            });
        }).on("mouseleave", function () {
        var _this = this;
        setTimeout(function () {
            if (!$(".popover:hover").length) {
                $(_this).popover("hide");
            }
        }, 300);
    });

    $("[data-toggle=hover]").popover({html: true})
    $('#popoverData').popover();
    /*$(document).ready(function () {
     $('table').footable();
     });*/

    function recargar() {
        window.location.reload(true);
    }

    $(".views").click(function () {
        console.log("CLIC ELIMINAR")
    });
    $(document).on("click", ".views", function () {
        var id = this.id;
        var view = $("#view" + id).val();
        swal({
                title: '<%= t('views.mess_view_title')%>  ' + '<%= t('views.vista')%>  ' + view + '?',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<%= t('views.mess_view_swall_confirm')%> ",
                cancelButtonText: "<%= t('views.mess_view_swall_cancel')%>",
                closeOnConfirm: false,
                closeOnCancel: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal({
                            title: '<%= t('views.mess_view_title2')%>',
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "<%= t('views.mess_view_swall_confirm')%> ",
                            cancelButtonText: "<%= t('views.mess_view_swall_cancel')%>",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.ajax({
                                    type: "POST",
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                                    },
                                    url: "/views/" + id,
                                    data: {"_method": "delete"},
                                })
                                //swal("<%= t('views.mess_view_swall')%>");
                                swal(
                                    {
                                        title: '<%= t('views.mess_view_swall')%>',
                                        type: "success",
                                        confirmButtonText: "OK",
                                    }, function (isConfirm) {
                                        if (isConfirm) {
                                            recargar();
                                        }
                                    })
                            } else {
                                swal("<%= t('views.mess_view_swall_cancel_1')%>");
                            }
                        })
                } else {
                    swal("<%= t('views.mess_view_swall_cancel_1')%>");
                }
            });
    })

</script>

app/views/views/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.new_view.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">

        <%= render 'form', view: @view %>

      </div>
    </div>
  </div>
  <br>
</div>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @view.name %>
</p>

<p>
  <strong>Crear:</strong>
  <%= @view.crear %>
</p>

<p>
  <strong>Editar:</strong>
  <%= @view.editar %>
</p>

<p>
  <strong>Eliminar:</strong>
  <%= @view.eliminar %>
</p>

<p>
  <strong>Leer:</strong>
  <%= @view.leer %>
</p>

<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>