config/routes.rb
Rails.application.routes.draw do
  filter :locale
  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users

  get '/:locale' => 'home#index'

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="text-center">
      <strong><%= t('all.powered')%></strong> KS Soluciones S.A. de C.V. &copy; 1998-2018
    </div>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if current_user.profile.present? %>
    <% @permisos = current_user.profile.permissions %>
    <% arreglo = Array.new %>
    <% @permisos.each do |per| %>
        <% id = per.id %>
        <% valor = {name: '', crear: 0, editar: 0, leer: 0, eliminar: 0} %>
        <% valor[:name] = per.view_name %>
        <% if per.crear.nil? %>
            <% valor[:crear] = 0 %>
        <% else %>
            <% valor[:crear] = per.crear %>
        <% end %>

        <% if per.editar.nil? %>
            <% valor[:crear] = 0 %>
        <% else %>
            <% valor[:editar] = per.editar %>
        <% end %>

        <% if per.leer.nil? %>
            <% valor[:leer] = 0 %>
        <% else %>
            <% valor[:leer] = per.leer %>
        <% end %>

        <% if per.eliminar.nil? %>
            <% valor[:eliminar] = 0 %>
        <% else %>
            <% valor[:eliminar] = per.eliminar %>
        <% end %>

        <% arreglo.push(valor) %>
    <% end %>

    <nav class="navbar-default navbar-static-side" role="navigation" style="position: fixed">
      <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
          <li class="nav-header">
            <div class="dropdown profile-element">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                              <h3>
                                <strong class="font-bold"><%= current_user.name %> <%= current_user.last_name %>  </strong><br>
                              </h3>

                              <%# if (current_user.nameProfile_id == 1) || (current_user.nameProfile_id > 1) %>

                            </span>
                          <span class="text-muted text-xs block cerrado" id="abre">Menu <b class="caret"></b></span>
                        </span>
              </a>

              <ul class="dropdown-menu animated fadeInRight m-t-xs" id="menu">
                <li>
                  <a href="#"><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe + t('all.edit'), edit_user_registration_path %></a>
                </li>

                <li>
                  <a href="#"><%= link_to '<i class="fa fa-sign-out"></i>'.html_safe + t('all.logout'), "/logout" %></a>
                </li>
              </ul>
            </div>
            <div class="logo-element">
              KS
            </div>
          </li>


          <li class="<%= 'active' if current_page?('/') %>">
            <%= link_to "/" do %>
                <i class="fa fa-home"></i> <span class="nav-label"><%= t('all.home') %></span>
            <% end %>

          </li>


              <% if arreglo[1][:crear] == 8  || arreglo[1][:editar] == 4 || arreglo[1][:leer] == 2 || arreglo[1][:eliminar] == 1 || arreglo[2][:crear] == 8 || arreglo[2][:editar] == 4 || arreglo[2][:leer] == 2 || arreglo[2][:eliminar] == 1 || arreglo[3][:crear] == 8 || arreglo[3][:editar] == 4 || arreglo[3][:leer] == 2 || arreglo[3][:eliminar] == 1 || arreglo[4][:crear] == 8 || arreglo[4][:editar] == 4 || arreglo[4][:leer] == 2 || arreglo[4][:eliminar] == 1 %>
                  <li class="<%= is_active_controller('users') %> <%= is_active_controller('profiles') %>">
                    <a href=""><i class="fa fa-cogs"></i><span class="nav-level"><%= t('all.settings_n') %></span>
                      <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level <%= is_active_controller('users') %>">

                      <% if arreglo[1][:crear] == 8 || arreglo[1][:editar] == 4 || arreglo[1][:leer] == 2 || arreglo[1][:eliminar] == 1 %>
                          <li class="<%= 'active' if current_page?('/users') %>">
                            <%= link_to '<i class="fa fa-users"></i>'.html_safe + t('all.user'), users_path %>
                          </li>
                      <% end %>

                      <% if arreglo[2][:crear] == 8 || arreglo[2][:editar] == 4 || arreglo[2][:leer] == 2 || arreglo[2][:eliminar] == 1 %>
                          <li class="<%= is_active_controller('profiles') %>">
                            <%= link_to '<i class="fa fa-user"></i>'.html_safe + t('all.profiles'), profiles_path %>
                          </li>
                      <% end %>

                      <% if arreglo[3][:crear] == 8 || arreglo[3][:editar] == 4 || arreglo[3][:leer] == 2 || arreglo[3][:eliminar] == 1 %>
                          <li class="<%= is_active_controller('areas') %>">
                            <%= link_to '<i class="fa fa-sticky-note"></i>'.html_safe + t('all.areas'), areas_path %>
                          </li>
                      <% end %>
                      <% if current_user.profile_id == "1" || current_user.profile_id == 1 %>
                          <% if arreglo[4][:crear] == 8 || arreglo[4][:editar] == 4 || arreglo[4][:leer] == 2 || arreglo[4][:eliminar] == 1 %>
                              <li class="<%= is_active_controller('views') %>">
                                <%= link_to '<i class="fa fa-desktop"></i>'.html_safe + t('all.views'), views_path %>
                              </li>
                          <% end %>
                      <% end %>
                    </ul>
                  </li>
              <% end %>


        </ul>
      </div>
    </nav>
<% else %>
<% end %>

<script>
    $("#abre").click(function () {
        var tiene = $(this).hasClass("cerrado")
        if (tiene == false) {
            $(this).removeClass("abierto")
            $(this).addClass("cerrado")
            $("#menu").hide();
        } else {
            $(this).removeClass("cerrado")
            $(this).addClass("abierto")
            $("#menu").show();
        }
    })

</script>

app/views/layouts/_topnavbar.html.erb
<!--Fixed Top Var -->
<!--<div class="row border-bottom" style="margin-bottom: 60px">-->
<div class="row border-bottom">
  <!--Fixed Top Var -->
  <!--<nav class="navbar navbar-static-top white-bg" role="navigation" style="position: fixed; min-width: -moz-available; min-width: -webkit-max-content; box-sizing: border-box;">-->
  <nav class="navbar navbar-static-top white-bg" role="navigation">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
      <!--<form role="search" class="navbar-form-custom" method="post" action="/">-->
      <!--<div class="form-group">-->
      <!--<input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />-->
      <!--</div>-->
      <!--</form>-->
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <span class="m-r-sm text-muted welcome-message"><%= t('views.sessions_new.welcome') %> </span>
      </li>

      <!--<%# if is_active_controller('loyalty_cards') %>-->
          <!--<li>-->
            <!--<%#= link_to image_tag("mexico.png", border: 0, :height => 12, width: 24), locale: :es, :id => params[:id] %>-->
          <!--</li>-->
          <!--<li>-->
            <!--<%#= link_to image_tag("eua.png", border: 0, :height => 12, width: 24), locale: :en, :id => params[:id] %>-->
          <!--</li>-->
      <!--<%# elsif is_active_controller('reports') %>-->
          <!--<li>-->
            <!--<%#= link_to image_tag("mexico.png", border: 0, :height => 12, width: 24), locale: :es, :id => params[:id] %>-->
          <!--</li>-->
          <!--<li>-->
            <!--<%#= link_to image_tag("eua.png", border: 0, :height => 12, width: 24), locale: :en, :id => params[:id] %>-->
          <!--</li>-->

      <!--<%# else %>-->


          <li>
            <%= link_to image_tag("mexico.png", border: 0, :height => 12, width: 24), locale: :es %>
          </li>
          <li>
            <%= link_to image_tag("eua.png", border: 0, :height => 12, width: 24), locale: :en %>

          </li>
      <% #end %>


      <li><i class="fa fa-sign-out"></i></li>

      <li> <%= link_to t('all.logout'), destroy_user_session_path, method: :delete %>

        <!--<a href="/logout?locale=<%#= params[:locale] %>"><%#= t('all.logout')%> </a>-->


      <li>
        <a class="right-sidebar-toggle">
        </a>
      </li>

    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'ks-clasico-icono.png' %>
    <title><%= t('all.profile_template') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= Gon::Base.render_data %>
  </head>

  <% if current_user %>

      <body class="pace-done">

      <!-- Wrapper-->
      <div id="wrapper">
        <%= render 'layouts/navigation' %>

        <!-- Navigation -->

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

          <!-- Page wrapper -->
          <%= render 'layouts/topnavbar' %>

          <!-- Main view  -->
          <% if notice %>
              <p class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <label><%= notice %></label></p>
          <% end %>
          <% if alert %>
              <p class="alert alert-danger alert-dismissible ">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <label id="msj"><%= alert %></label></p>
          <% end %>
          <%= yield %>

          <!-- Footer -->
          <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

      </div>
      <!-- End wrapper-->

      </body>

  <% else %>

      <body style="background-color: #f3f3f4;">

      <%#= current_user.name %>

      <% if notice %>
          <div class="container">
            <div class="alert alert-success alert-dismissable">
              <p>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <label><%= notice %></label></p>
            </div>
          </div>
      <% elsif alert %>
          <!--<<div class="ibox-content ">-->
          <div class="container">
            <div class="alert alert-danger alert-dismissable">
              <p>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <label id="msj"><%= alert %></label></p>
            </div>
          </div>


      <% end %>
      <div>
        <div class="row">

          <div class="col-md-3"></div>
          <div class="col-md-6">
            <%= yield %>
          </div>
          <div class="col-md-3">
            <p><br><br><br><br></p>
            <%= link_to t('views.sessions_new.reactivation'), expired_accounts_new_path, :class => 'btn btn-danger', :id => "activarCuenta", :style => "display:none" %>
          </div>

        </div>
      </div>
  <% end %>

  </body>
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
  <%= yield :stylesheet %>
  <%= yield :javascript %>
</html>